name: user_repository
description: "The repo that handles the users"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  rxdart: 0.28.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
